# Generated by Django 5.0.1 on 2024-02-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('TO DO', 'TO DO'), ('COMPLETED', 'COMPLETED'), ('IN-PROGRESS', 'IN-PROGRESS')], default='TO DO', max_length=50, null=True)),
            ],
        ),
    ]
